server:
  port: 8081
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root@root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




